'''
Author: Hubert Waleńczak

Description:
This script is designed to generate and save a CSV file containing attendance records for each day. It operates on CSV files located in the 'Attendance' folder, with each file named after the corresponding date generated by the 'CheckAttendance.py' script. The attendance records are based on a master CSV file named 'Students.csv,' which should include students names and a column named 'student_number' with their unique identifiers.

Requirements:
- pandas
- 'Students.csv' file with students' information
- 'Attendance' folder containing CSV files named after the date

Arguments:
--name [output_file_name]
    Specify the name of the output file (without '.csv') to save the attendance records.
    Default: 'BlockAttendance'

Example Usage:
python script_name.py --name BlockA
'''

import pandas as pd
Attendance = pd.read_csv('data.csv')
Students = pd.read_csv('Students.csv')
Date = Attendance.iloc[0,0].split()
Present = Students.merge(Attendance, on='student_number', how='inner')
del Present['date']
Present.to_csv('Attendance'+Date[0]+'.csv', sep=',', index=False)
